version: "3.9"
services:
  mysql-db:
    image: "mysql:latest"
    container_name: mysql-8
    restart: always
    ports:
      - '3307:3306'
    networks:
      - 'springapimysql-net'
    environment:
      - 'MYSQL_DATABASE=csekuaa'
      - 'MYSQL_PASSWORD=cseku@2023'
      - 'MYSQL_ROOT_PASSWORD=cseku@2023'
      - 'MYSQL_USER=csekuaa'
    volumes:
      - db:/var/lib/mysql

  cse_kuaa_backend:
    build: .
    container_name: cse_kuaa_backend
    restart: always
    env_file: ./.env
    environment:
     - spring.datasource.url=jdbc:mysql://mysql-db:3307/csekuaa
     - spring.datasource.username=csekuaa
     - spring.datasource.password=cseku@2023
     - spring.jpa.hibernate.ddl-auto=auto
    ports:
      - '8081:8080'
    networks:
      - 'springapimysql-net'
    depends_on:
      - mysql-db


networks:
  springapimysql-net:
volumes:
  db: